name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: 21

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['22.x']
        os: [ubuntu-latest, windows-2022, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run CI tests
        run: npm run test:ci
